#!/bin/bash -eu
usage() { echo "$0 usage:" && grep " .*)\ #" $0; exit 0; }
NO_CACHE_OPT=''
options=$(getopt -l "help,no-cache" -o "h" -a -- "$@")
eval set -- "$options"

while true; do
    case $1 in
        -h|--help) # Display help
            usage
            ;;
        --no-cache) # Disable cache
            NO_CACHE_OPT=' --ignore-build-cache'
        ;;
        --)
            shift
            break;;
    esac
    shift
done



pushd "."
set -x
MLV_PY_CMD_PATH="poc/pipeline/steps/mlvtools_02_tokenize_text.py"
MLV_PY_CMD_NAME="mlvtools_02_tokenize_text.py"
INPUT_CSV_FILE="./poc/data/data_train.csv"
OUTPUT_CSV_FILE="./poc/data/data_train_tokenized.csv"

# META FILENAME, MODIFY IF DUPLICATE
MLV_DVC_META_FILENAME="./mlvtools_02_tokenize_text.dvc"

dvc run${NO_CACHE_OPT} --overwrite-dvcfile -f $MLV_DVC_META_FILENAME \
-d $INPUT_CSV_FILE \
-o $OUTPUT_CSV_FILE \
poc/pipeline/steps/mlvtools_02_tokenize_text.py --input-csv-file $INPUT_CSV_FILE --output-csv-file $OUTPUT_CSV_FILE


popd