#!/bin/bash -eu
usage() { echo "$0 usage:" && grep " .*)\ #" $0; exit 0; }
NO_CACHE_OPT=''
options=$(getopt -l "help,no-cache" -o "h" -a -- "$@")
eval set -- "$options"

while true; do
    case $1 in
        -h|--help) # Display help
            usage
            ;;
        --no-cache) # Disable cache
            NO_CACHE_OPT=' --ignore-build-cache'
        ;;
        --)
            shift
            break;;
    esac
    shift
done



pushd "."
set -x
MLV_PY_CMD_PATH="poc/pipeline/steps/mlvtools_04_evaluate_model.py"
MLV_PY_CMD_NAME="mlvtools_04_evaluate_model.py"
DATA_FILE="./poc/data/data_train_tokenized.csv"
MODEL_FILE="./poc/data/fasttext_model.bin"
RESULT_FILE="./poc/data/metrics.txt"

# META FILENAME, MODIFY IF DUPLICATE
MLV_DVC_META_FILENAME="./mlvtools_04_evaluate_model.dvc"

dvc run${NO_CACHE_OPT} --overwrite-dvcfile -f $MLV_DVC_META_FILENAME \
-d $DATA_FILE \
-d $MODEL_FILE \
-o $RESULT_FILE \
poc/pipeline/steps/mlvtools_04_evaluate_model.py --data-file $DATA_FILE --model-file $MODEL_FILE --result-file $RESULT_FILE


popd